language: java

jdk:
  - oraclejdk8

os:
  - linux
  - osx

osx_image: xcode9.3

addons:
  apt:
    packages:
      - fakeroot

before_install:
  - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

script:
  - "./gradlew assemble"
  - "./gradlew clean check -Dmockserver.logLevel=ERROR"

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  except:
    - gh-pages
    - docs

before_deploy:
  - "./gradlew jfxJar"
  - "./gradlew jfxNative"
  - "mv build/jfx/app/project-jfx.jar build/jfx/app/octopusdownloader.jar"

deploy:
  - provider: releases
    api_key: $GITHUB_API_KEY
    skip_cleanup: true
    draft: true
    file_glob: true
    file:
      - build/jfx/native/*.pkg
      - build/jfx/native/*.dmg
      - build/jfx/native/*.app
    on:
      condition: $TRAVIS_OS_NAME = osx
      branch: release
      tags: true

  - provider: releases
    api_key: $GITHUB_API_KEY
    skip_cleanup: true
    file_glob: true
    file:
      - build/jfx/app/*.jar
      - build/jfx/native/*.deb
    draft: true
    on:
      condition: $TRAVIS_OS_NAME = linux
      branch: release
      tags: true