language: java
jdk:
  - oraclejdk8
os:
- linux
- osx
osx_image: xcode9.3
before_install:
  - chmod +x gradlew
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
script:
  - "./gradlew assemble"
  - "./gradlew clean check -Dmockserver.logLevel=ERROR"
after_success:
- bash <(curl -s https://codecov.io/bash)
branches:
  except:
  - gh-pages
  - docs

before_deploy:
  - "./gradlew jfxNative"

deploy:
  - provider: releases
    api_key:
      secure: LySWVSDg3S22HWo+/L/ig/hJjj4bkeXq/UEXQSr7+uHw2lBe7Up0b9bxE4Nl7W6OInZcRKWDl8NoIMQvNV2+aEknGw3RcJZgM24GgsgOjXqoYh3TPh7S88e0fHd8/Fp3uNt/81R90OqeEOl6bEMA2r7a3lZbDpb/fh9OZHeX5uZYZK/UQgc1mz9+zLJVxwwB2FkeEf3Xqe7kDCZj0d/tuTL6De/jLRUfx9x2jxlLHnTve6OjgkSnVxiML8p463Bv+WqRNIKoJiZmLiQbUzpSYA19jzLmmpIx8cSFFAcxMnSamXZbP8RMQHDKnnV46HRMl3rJOAYIcdtM0DYYwxrfzBug/RMsPA/ShW8mSZWkDB9BfwoHm9INo9mfzlo04fC32OIMPSFqZfj3QGwHbIVAHuu1pKfdVGPl83Pra7vJ426n894tEVeZU/91aa5vLRx4WOZ26yncm83Cbfr0I5EtBK9hD4h+oeAKLX6Iim3z6i3Ij3MsKyagFM18fyyBwT65AK7keQ6oHW0NtgAk6GCkiyj++l2EYYUCnr0kaAhkFAbW4N9hspaaa2uoUX++T0RAGz7zBueqew2ntblxyThwnFEf2zSu17MK8P8z0Qy5I7s2kP0GNJSDnkj4IilOEquNNJg4umhEuAg2xDhnTUHwhuqJK1SJZXrD7v5xP9mcAPk=
    skip_cleanup: true
    file: "build/jfx/native/octopusdownloader-*.app"
    on:
      condition: $TRAVIS_OS_NAME = osx
      branch: release
      tags: true

  - provider: releases
    api_key:
      secure: LySWVSDg3S22HWo+/L/ig/hJjj4bkeXq/UEXQSr7+uHw2lBe7Up0b9bxE4Nl7W6OInZcRKWDl8NoIMQvNV2+aEknGw3RcJZgM24GgsgOjXqoYh3TPh7S88e0fHd8/Fp3uNt/81R90OqeEOl6bEMA2r7a3lZbDpb/fh9OZHeX5uZYZK/UQgc1mz9+zLJVxwwB2FkeEf3Xqe7kDCZj0d/tuTL6De/jLRUfx9x2jxlLHnTve6OjgkSnVxiML8p463Bv+WqRNIKoJiZmLiQbUzpSYA19jzLmmpIx8cSFFAcxMnSamXZbP8RMQHDKnnV46HRMl3rJOAYIcdtM0DYYwxrfzBug/RMsPA/ShW8mSZWkDB9BfwoHm9INo9mfzlo04fC32OIMPSFqZfj3QGwHbIVAHuu1pKfdVGPl83Pra7vJ426n894tEVeZU/91aa5vLRx4WOZ26yncm83Cbfr0I5EtBK9hD4h+oeAKLX6Iim3z6i3Ij3MsKyagFM18fyyBwT65AK7keQ6oHW0NtgAk6GCkiyj++l2EYYUCnr0kaAhkFAbW4N9hspaaa2uoUX++T0RAGz7zBueqew2ntblxyThwnFEf2zSu17MK8P8z0Qy5I7s2kP0GNJSDnkj4IilOEquNNJg4umhEuAg2xDhnTUHwhuqJK1SJZXrD7v5xP9mcAPk=
    skip_cleanup: true
    file: "build/jfx/native/octopusdownloader-*.deb"
    on:
      condition: $TRAVIS_OS_NAME = linux
      branch: release
      tags: true