build:
  verbosity: detailed

build_script:
- gradlew.bat assemble

test_script:
- gradlew.bat check -Dmockserver.logLevel=OFF

branches:
  except:
  - docs
  - gh-pages

cache:
- C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0


matrix:
  fast_finish: true