build:
  verbosity: detailed

build_script:
- gradlew.bat assemble

test_script:
- gradlew.bat check -Dmockserver.logLevel=ERROR

branches:
  except:
  - docs
  - gh-pages

cache:
- C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0


matrix:
  fast_finish: true

before_deploy:
  - gradlew.bat jfxNative

artifacts:
  - path: build\jfx\native\*.exe
    name: App

deploy:
  provider: GitHub
  auth_token:
    secure: EcvZUzeHW3GeSNJRIgPmFXXKWK82LcckWy2AkCYYUJFDg2Rxcpg9VXE9UfFq6vtu
  artifact: build\jfx\native\*.exe
  draft: true
  on:
    APPVEYOR_REPO_TAG: true
