build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble

test_script:
  - gradlew.bat check -Dmockserver.logLevel=ERROR

after_test:
  - winrelease.bat

branches:
  except:
  - docs
  - gh-pages

cache:
- C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: true

artifacts:
  - path: build\jfx\native\*.exe
    name: App

deploy:
  - provider: GitHub
    auth_token:
      secure: EcvZUzeHW3GeSNJRIgPmFXXKWK82LcckWy2AkCYYUJFDg2Rxcpg9VXE9UfFq6vtu
    artifact: App
    draft: true
    on:
      APPVEYOR_REPO_TAG: true
